//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agap2IT.Labs.BlockBase.BBLinq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("agap2IT.Labs.BlockBase.BBLinq.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/ExecuteQuery.
        /// </summary>
        internal static string PATH_EXECUTE_QUERY {
            get {
                return ResourceManager.GetString("PATH_EXECUTE_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Requester/ExecuteQuery.
        /// </summary>
        internal static string PATH_EXECUTE_QUERY_TO_CONTENT {
            get {
                return ResourceManager.GetString("PATH_EXECUTE_QUERY_TO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Requester/GetStructure.
        /// </summary>
        internal static string PATH_GET_STRUCTURE {
            get {
                return ResourceManager.GetString("PATH_GET_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string QUERY_ADD {
            get {
                return ResourceManager.GetString("QUERY_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER.
        /// </summary>
        internal static string QUERY_ALTER {
            get {
                return ResourceManager.GetString("QUERY_ALTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string QUERY_AND {
            get {
                return ResourceManager.GetString("QUERY_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLUMN.
        /// </summary>
        internal static string QUERY_COLUMN {
            get {
                return ResourceManager.GetString("QUERY_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string QUERY_CREATE {
            get {
                return ResourceManager.GetString("QUERY_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        internal static string QUERY_DATABASE {
            get {
                return ResourceManager.GetString("QUERY_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string QUERY_DELETE {
            get {
                return ResourceManager.GetString("QUERY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        internal static string QUERY_DIFFERENT {
            get {
                return ResourceManager.GetString("QUERY_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP.
        /// </summary>
        internal static string QUERY_DROP {
            get {
                return ResourceManager.GetString("QUERY_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCRYPTED.
        /// </summary>
        internal static string QUERY_ENCRYPTED {
            get {
                return ResourceManager.GetString("QUERY_ENCRYPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string QUERY_END {
            get {
                return ResourceManager.GetString("QUERY_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string QUERY_EQUAL_OR_GREATER {
            get {
                return ResourceManager.GetString("QUERY_EQUAL_OR_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string QUERY_EQUAL_OR_LESS {
            get {
                return ResourceManager.GetString("QUERY_EQUAL_OR_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string QUERY_EQUALS {
            get {
                return ResourceManager.GetString("QUERY_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string QUERY_FIELD_SEPARATOR {
            get {
                return ResourceManager.GetString("QUERY_FIELD_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string QUERY_FIELD_WRAPPER_LEFT {
            get {
                return ResourceManager.GetString("QUERY_FIELD_WRAPPER_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string QUERY_FIELD_WRAPPER_RIGHT {
            get {
                return ResourceManager.GetString("QUERY_FIELD_WRAPPER_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string QUERY_FROM {
            get {
                return ResourceManager.GetString("QUERY_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string QUERY_GREATER {
            get {
                return ResourceManager.GetString("QUERY_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string QUERY_INSERT {
            get {
                return ResourceManager.GetString("QUERY_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTO.
        /// </summary>
        internal static string QUERY_INTO {
            get {
                return ResourceManager.GetString("QUERY_INTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        internal static string QUERY_JOIN {
            get {
                return ResourceManager.GetString("QUERY_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string QUERY_LESS {
            get {
                return ResourceManager.GetString("QUERY_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string QUERY_ON {
            get {
                return ResourceManager.GetString("QUERY_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string QUERY_OR {
            get {
                return ResourceManager.GetString("QUERY_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE.
        /// </summary>
        internal static string QUERY_RANGE {
            get {
                return ResourceManager.GetString("QUERY_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAME.
        /// </summary>
        internal static string QUERY_RENAME {
            get {
                return ResourceManager.GetString("QUERY_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string QUERY_SELECT {
            get {
                return ResourceManager.GetString("QUERY_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .*.
        /// </summary>
        internal static string QUERY_SELECT_ALL {
            get {
                return ResourceManager.GetString("QUERY_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET.
        /// </summary>
        internal static string QUERY_SET {
            get {
                return ResourceManager.GetString("QUERY_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string QUERY_TABLE {
            get {
                return ResourceManager.GetString("QUERY_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string QUERY_TABLE_FIELD_SEPARATOR {
            get {
                return ResourceManager.GetString("QUERY_TABLE_FIELD_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string QUERY_TEXT_WRAPPER_LEFT {
            get {
                return ResourceManager.GetString("QUERY_TEXT_WRAPPER_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string QUERY_TEXT_WRAPPER_RIGHT {
            get {
                return ResourceManager.GetString("QUERY_TEXT_WRAPPER_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        internal static string QUERY_TO {
            get {
                return ResourceManager.GetString("QUERY_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string QUERY_UPDATE {
            get {
                return ResourceManager.GetString("QUERY_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE.
        /// </summary>
        internal static string QUERY_USE {
            get {
                return ResourceManager.GetString("QUERY_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string QUERY_VALUE_ASSIGNER {
            get {
                return ResourceManager.GetString("QUERY_VALUE_ASSIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUES.
        /// </summary>
        internal static string QUERY_VALUES {
            get {
                return ResourceManager.GetString("QUERY_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        internal static string QUERY_WHERE {
            get {
                return ResourceManager.GetString("QUERY_WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string REQUEST_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("REQUEST_CONTENT_TYPE", resourceCulture);
            }
        }
    }
}
